# Generated by Django 5.1.3 on 2024-11-12 08:46

from django.db import migrations

def rename_total_score_key(apps, schema_editor):
    UserProfile = apps.get_model('sim', 'UserProfile') 
    for profile in UserProfile.objects.all():
        categories_performance = profile.categories_performance

        for category, data in categories_performance.items():
            if 'total score' in data:
                data['total_score'] = data.pop('total score') 

        profile.categories_performance = categories_performance
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_category_question_option'),
    ]

    operations = [
         migrations.RunPython(rename_total_score_key),
    ]
